name: Check for new Nginx Helm chart version

on:
  push:
    branches:
      - main

jobs:
  check-for-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v1
      - name: Add Helm repo
        run: helm repo add stable https://charts.helm.sh/stable
      - name: Update Helm repo
        run: helm repo update
      - name: Check for new version
        uses: helm/chart-releaser-action@latest
        with:
          chart: stable/nginx
          owner: bplasmeijer
          token: ${{ secrets.GITHUB_TOKEN }}
