#!/bin/bash

# This is a basic workflow to help you get started with Actions

name: provision

# Controls when the workflow will run
on:

  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment'     
        required: true
        type: choice
        options:
          - shared
        default: 'shared'
      name:
        description: 'name'     
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  check-variables:

    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          echo "environment: ${{ github.event.inputs.environment }}"
          echo "name: ${{ github.event.inputs.name }}" 

  # This workflow contains a single job called "provision"
  provision:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Set the environment scope
    environment:  ${{ github.event.inputs.environment }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run
        run: |
          echo "environment: ${{ github.event.inputs.environment }}"
          echo "name: ${{ github.event.inputs.name }}" 

 
          export ENVIRONMENT="${{ github.event.inputs.environment }}"
          export NAME="${{ github.event.inputs.name }}"

          ./scripts/provision.sh 
