#!/bin/bash

# This is a basic workflow to help you get started with Actions

name: main

# Controls when the workflow will run
on:

  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment'     
        required: true
        type: choice
        options:
          - shared
          - unified
          - ch
          - xmcloud
        default: 'shared'
      region:
        description: 'region'     
        required: true
        type: choice
        options:
          - euw
          - use
        default: 'euw'
      typeof:
        description: 'typeof'     
        required: true
        type: choice
        options:
          - internal
          - external
        default: 'internal'
      name:
        description: 'name'     
        required: true
        type: choice
        options:
          - ${{ github.event.inputs.region }}-e1-${{ github.event.inputs.typeof }}-${{ github.event.inputs.environment }}-blue
          - ${{ github.event.inputs.region }}-e1-${{ github.event.inputs.typeof }}-${{ github.event.inputs.environment }}-green

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          echo "environment: ${{ github.event.inputs.environment }}"
          echo "name: ${{ github.event.inputs.name }}" 

  # This workflow contains a single job called "provision"
  provision:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Set the environment scope
    environment:  ${{ github.event.inputs.environment }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout fleet
        uses: actions/checkout@v4
        with:
          path: main

      - name: ls fleet
        run: |
          ls -la main

      - name: checkout flux
        uses: actions/checkout@v4
        with:
          repository: bplasmeijer/component.flux-system
          path: flux

      - name: ls flux
        run: |
          ls -la flux
  
      - name: install flux
        run: |
          curl -s https://fluxcd.io/install.sh | sudo FLUX_VERSION=0.37.0 bash
      
      # make kind test cluster
      - name: create-kind
        run: |
          echo "environment: ${{ github.event.inputs.environment }}"
          echo "name: ${{ github.event.inputs.name }}" 
 
          export ENVIRONMENT="${{ github.event.inputs.environment }}"
          export NAME="${{ github.event.inputs.name }}"

          ./main/scripts/kind.sh 

      # delete kind test cluster
      - name: delete-kind
        run: |
          ./main/scripts/cleanup.sh 
